SERVER-91980 Fix Abseil pretty printers (#24971)
Same fix as
[here](https://github.com/visemet/gdb-mongodb-server/blob/v0.15.1/gdbmongo/abseil_printers.py#L48-L67).
As Max's comment states, the `absl_get_settings` will disambiguate what
value needs to be accessed. We cast a Storage type (which stores the 0th
index of
[`settings_`](https://github.com/mongodb/mongo/blob/77a98db3c5d32a58b9782b63e2484978641f1b71/src/third_party/abseil-cpp/dist/absl/container/internal/raw_hash_set.h#L2799)
aka `CommonFields`).

Tested by locally printing `cat->_sessions` with this dummy test:
```
TEST_F(SessionCatalogTest, GDBPrettyPrintTest) {
    auto cat = catalog();
    auto lsid = LogicalSessionId();
    cat->_sessions.insert({lsid, std::make_unique<SessionCatalog::SessionRuntimeInfo>(lsid)});
    while (1) {
    }
}
```

This previously outputted:
```
(gdb) p cat->_sessions
$1 = Traceback (most recent call last):
  File "buildscripts/gdb/mongo_printers.py", line 655, in to_string
    absl_container_size(self.val),
  File "buildscripts/gdb/mongo_printers.py", line 559, in absl_container_size
    return val["settings_"]["value"]["compressed_tuple_"]["value"]
gdb.error: Request for member 'value' is ambiguous in type 'absl::lts_20230802::container_internal::CompressedTuple<absl::container_internal::CommonFields, mongo::HashImprover<mongo::LogicalSessionIdHash, mongo::LogicalSessionId>, std::equal_to<mongo::LogicalSessionId>, std::allocator<std::pair<mongo::LogicalSessionId const, std::unique_ptr<mongo::SessionCatalog::SessionRuntimeInfo, std::default_delete<mongo::SessionCatalog::SessionRuntimeInfo> > > > >'. Candidates are:
  'absl::lts_20230802::container_internal::CommonFields absl::lts_20230802::container_internal::internal_compressed_tuple::Storage<absl::container_internal::CommonFields, 0, false>::value' (absl::lts_20230802::container_internal::CompressedTuple<absl::container_internal::CommonFields, mongo::HashImprover<mongo::LogicalSessionIdHash, mongo::LogicalSessionId>, std::equal_to<mongo::LogicalSessionId>, std::allocator<std::pair<mongo::LogicalSessionId const, std::unique_ptr<mongo::SessionCatalog::SessionRuntimeInfo, std::default_delete<mongo::SessionCatalog::SessionRuntimeInfo> > > > > -> absl::lts_20230802::container_internal::internal_compressed_tuple::CompressedTupleImpl<absl::container_internal::CompressedTuple<absl::container_internal::CommonFields, mongo::HashImprover<mongo::LogicalSessionIdHash, mongo::LogicalSessionId>, std::equal_to<mongo::LogicalSessionId>, std::allocator<std::pair<mongo::LogicalSessionId const, std::unique_ptr<mongo::SessionCatalog::SessionRuntimeInfo, std::default_delete<mongo::SessionCatalog::SessionRuntimeInfo> > > > >, absl::integer_sequence<unsigned long, 0, 1, 2, 3>, true> -> absl::lts_20230802::container_internal::internal_compressed_tuple::Storage<absl::container_internal::CommonFields, 0, false>)
  'mongo::HashImprover<mongo::LogicalSessionIdHash, mongo::LogicalSessionId> absl::lts_20230802::container_internal::internal_compressed_tuple::Storage<mongo::HashImprover<mongo::LogicalSessionIdHash, mongo::LogicalSessionId>, 1, false>::value' (absl::lts_20230802::container_internal::CompressedTuple<absl::container_internal::CommonFields, mongo::HashImprover<mongo::LogicalSessionIdHash, mongo::LogicalSessionId>, std::equal_to<mongo::LogicalSessionId>, std::allocator<std::pair<mongo::LogicalSessionId const, std::unique_ptr<mongo::SessionCatalog::SessionRuntimeInfo, std::default_delete<mongo::SessionCatalog::SessionRuntimeInfo> > > > > -> absl::lts_20230802::container_internal::internal_compressed_tuple::CompressedTupleImpl<absl::container_internal::CompressedTuple<absl::container_internal::CommonFields, mongo::HashImprover<mongo::LogicalSessionIdHash, mongo::LogicalSessionId>, std::equal_to<mongo::LogicalSessionId>, std::allocator<std::pair<mongo::LogicalSessionId const, std::unique_ptr<mongo::SessionCatalog::SessionRuntimeInfo, std::default_delete<mongo::SessionCatalog::SessionRuntimeInfo> > > > >, absl::integer_sequence<unsigned long, 0, 1, 2, 3>, true> -> absl::lts_20230802::container_internal::internal_compressed_tuple::Storage<mongo::HashImprover<mongo::LogicalSessionIdHash, mongo::LogicalSessionId>, 1, false>
```

Now this outputs:
```
(gdb) p cat->_sessions
$1 = absl::node_hash_map<mongo::LogicalSessionId, std::unique_ptr<mongo::SessionCatalog::SessionRuntimeInfo, std::default_delete<mongo::SessionCatalog::SessionRuntimeInfo> >> with 1 elems  = {[{static fieldNames = {_M_elems = {"id", "uid", "txnNumber", "txnUUID", "serialization_context"}}, static kIdFieldName = {static npos = 18446744073709551615, _sv = "id"}, static kTxnNumberFieldName = {static npos = 18446744073709551615, _sv = "txnNumber"}, static kTxnUUIDFieldName = {static npos = 18446744073709551615, _sv = "txnUUID"}, static kUidFieldName = {static npos = 18446744073709551615, _sv = "uid"}, _serializationContext = {_source = mongo::SerializationContext::Source::Default, _callerType = mongo::SerializationContext::CallerType::None, _prefixState = mongo::SerializationContext::Prefix::ExcludePrefix}, _id = "00000000-0000-0000-0000-", '0' <repeats 12 times>, _uid = {static kHashLength = <optimized out>, static kName = <optimized out>, _hash = {_data = {_M_elems = '\000' <repeats 31 times>}}}, _txnNumber = , _txnUUID = , _hasMembers = {_hasField = std::bitset}, static _isCommandReply = false}] = std::unique_ptr<mongo::SessionCatalog::SessionRuntimeInfo> = {get() = 0x51b17fc72fd0}}
```