SERVER-102292: label the -Wstringop-overflow atomic store workaround (#34345)
GCC 14 warns about a buffer overflow when performing an atomic store on
x86 Linux:
```
In member function 'void std::__atomic_base<_IntTp>::store(__int_type, std::memory_order) [with _ITp = bool]',
    inlined from 'void std::atomic<bool>::store(bool, std::memory_order)' at external/mongo_toolchain_v5/stow/gcc-v5/include/c++/14.2.0/atomic:109:20,
    inlined from 'void mongo::atomic_detail::Base<T, mongo::atomic_detail::Category::kBasic>::store(WordType) [with T = bool]' at src/mongo/platform/atomic.h:104:21,
    inlined from 'void mongo::logv2::LogCaptureBackend::setEnabled(bool)' at src/mongo/logv2/log_capture_backend.h:79:23,
    inlined from 'void mongo::unittest::{anonymous}::CaptureLogs::startCapturingLogMessages()' at src/mongo/unittest/unittest.cpp:300:51,
    inlined from 'void mongo::unittest::Test::startCapturingLogMessages()' at src/mongo/unittest/unittest.cpp:401:48:
external/mongo_toolchain_v5/stow/gcc-v5/include/c++/14.2.0/bits/atomic_base.h:477:25: error: 'void __atomic_store_1(volatile void*, unsigned char, int)' writing 1 byte into a region of size 0 overflows the destination [-Werror=stringop-overflow=]
  477 |         __atomic_store_n(&_M_i, __i, int(__m));
      |         ~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~
In member function 'void mongo::unittest::Test::startCapturingLogMessages()':
cc1plus: note: destination object is likely at address zero
```
This warning is likely spurious, and is probably related to the [similar
case][1] when performing an atomic load (instead of a store). See, in
particular, jpbronsted's [comment][2].

We were already selectively ignoring this warning. This commit gives the
workaround macro a more specific name (`
MONGO_COMPILER_DIAGNOSTIC_WORKAROUND_ATOMIC_WRITE`) so that
`MONGO_COMPILER_DIAGNOSTIC_IGNORED_TRANSITIONAL` can eventually be
[removed][3].

[1]: https://github.com/10gen/mongo/pull/29694
[2]: https://github.com/10gen/mongo/pull/29694#discussion_r1861369347
[3]: https://jira.mongodb.org/browse/SERVER-102303

Co-authored-by: David Goffredo <david.goffredo@mongodb.com>